# If the variables are the same, but are named differently in
# the netCDF files, use the yaml key as the "homogenizing" key, and
# list the alternative name in "alternative_names".
# This pipeline will rename the alternative name to the yaml key if found.
# E.g. if the lr and hr datasets have different
# numbers of covariates, e.g. Annau et al. 2023, then
# you can specify if a variable only occurs in the hr or lr
# dataset respectively with hr_only or lr_only: true
# The same logic above applies for the dimensions, dims, and coordinates, coords.

hr_grid_ref_path: "/Users/susanbeale/Desktop/susan_data/med_wind_small_hs/hs/hs_nonan_199501_waves_r1i1p2f1_CanESM5orig_hist_smallest.nc"

vars:
  hs:
    hr:
      path: /Users/susanbeale/Desktop/susan_data/med_wind_small_hs/hs/*smallest.nc
      is_west_negative: false
    lr:
      path: /Users/susanbeale/Desktop/susan_data/med_wind_small_hs/hs/*smallest.nc
      is_west_negative: false
    output_path: /Users/susanbeale/Desktop/95_97_med_w_small_hs/
    alternative_names: ["hs","SWH"]
    standardize: true

  uas:
    hr:
      path: /Users/susanbeale/Desktop/susan_data/med_wind_small_hs/uas/*mid.nc
      is_west_negative: false
    lr:
      path: /Users/susanbeale/Desktop/susan_data/med_wind_small_hs/uas/*mid.nc
      is_west_negative: false
    output_path: /Users/susanbeale/Desktop/95_97_med_w_small_hs/
    alternative_names: ["U10", "u10", "uas","uwnd"]
    standardize: true

  vas:
    hr:
      path: /Users/susanbeale/Desktop/susan_data/med_wind_small_hs/vas/*mid.nc
      is_west_negative: false
    lr:
      path: /Users/susanbeale/Desktop/susan_data/med_wind_small_hs/vas/*mid.nc
      is_west_negative: false
    output_path: /Users/susanbeale/Desktop/95_97_med_w_small_hs/
    alternative_names: ["V10", "v10", "vas","vwnd"]
    standardize: true

#  ice:
#    hr:
#      path: /Users/susanbeale/Desktop/susan_data/ice/*smallest.nc
#      is_west_negative: false
#    lr:
#      path: /Users/susanbeale/Desktop/susan_data/ice/*smallest.nc
#      is_west_negative: false
#    output_path: /Volumes/LaCie/2year_coarsened_cropped/
#    alternative_names: ["ice","SIC"]
#    standardize: true
#
#  t0m1:
#    hr:
#      path: /Users/susanbeale/Desktop/susan_data/t0m1/*smallest.nc
#      is_west_negative: false
#    lr:
#      path: /Users/susanbeale/Desktop/susan_data/t0m1/*smallest.nc
#      is_west_negative: false
#    output_path: /Volumes/LaCie/2year_coarsened_cropped/
#    alternative_names: ["t0m1"]
#    standardize: true
#
#  dir:
#    hr:
#      path: /Users/susanbeale/Desktop/susan_data/dir/*smallest.nc
#      is_west_negative: false
#    lr:
#      path: /Users/susanbeale/Desktop/susan_data/dir/*smallest.nc
#      is_west_negative: false
#    output_path: /Volumes/LaCie/2year_coarsened_cropped/
#    alternative_names: ["dir"]
#    standardize: true
#

  # MAPSTA:
  #   hr:
  #     path: /Users/susanbeale/Desktop/susan_data/MAPSTA/*small3.nc
  #     is_west_negative: false
  #   lr:
  #     path: /Users/susanbeale/Desktop/susan_data/MAPSTA/*small3.nc
  #     is_west_negative: false
  #   output_path: /Volumes/LaCie/2years_smallest_coarsened_southatlantic/
  #   alternative_names: ["MAPSTA"]
  #   standardize: true

dims:
  time:
    alternative_names: ["Time", "Times", "times"]
  rlat:
    alternative_names: ["rotated_latitude"]
    hr_only: true
  rlon:
    alternative_names: ["rotated_longitude"]
    hr_only: true
coords:
  lat:
    alternative_names: ["latitude", "Lat", "Latitude"]
  lon:
    alternative_names: ["longitude", "Long", "Lon", "Longitude"]

# Time indexing for subsets
time:
  # Crop to the dataset with the shortest run
  # this defines the full dataset from which to subset
  full:
    start: "19950101T00:00:00"
    end: "19971231T21:00:00"

  # use this to select which years to reserve for testing and validation
  # the remaining years in full will be used for training
  # include validation years in test years they are separated during preprocessing
  test_years: [1996,1997]
  validation_years: [1997]

# sets the scale factor and index slices of the rotated coordinates
spatial:
  scale_factor: 16
  x:
    first_index: 64
    last_index: 192
  y:
    first_index: 64
    last_index: 192

# xarray netcdf engine
engine: h5netcdf
steps_per_file: 32
randomize: true

# dask client parameters
compute:
  threads_per_worker: 1
  memory_limit: "8GB"
  dashboard_address: 8787

# define torch
loader:
  batch_size: 50
  randomize: true
  seed: 0
