# If the variables are the same, but are named differently in
# the netCDF files, use the yaml key as the "homogenizing" key, and
# list the alternative name in "alternative_names".
# This pipeline will rename the alternative name to the yaml key if found.
# E.g. if the lr and hr datasets have different
# numbers of covariates, e.g. Annau et al. 2023, then
# you can specify if a variable only occurs in the hr or lr
# dataset respectively with hr_only or lr_only: true
# The same logic above applies for the dimensions, dims, and coordinates, coords.

hr_grid_ref_path: "/Volumes/LaCie/nonan/hs/hs_nonan_199501_waves_r1i1p2f1_CanESM5orig_hist_small3.nc"

vars:
  hs:
    hr:
      path: /Volumes/LaCie/nonan/hs/*small3.nc
      is_west_negative: false
    lr:
      path: /Volumes/LaCie/nonan/hs/*small3.nc
      is_west_negative: false
    output_path: /Volumes/LaCie/2years_smallest_coarsened_southatlantic/
    alternative_names: ["hs","SWH"]
    standardize: true
    hr_only: true 

  uas:
    hr:
      path: /Volumes/LaCie/nonan/uas/*small3.nc
      is_west_negative: false
    lr:
      path: /Volumes/LaCie/nonan/uas/*small3.nc
      is_west_negative: false
    output_path: /Volumes/LaCie/2years_smallest_coarsened_southatlantic/
    alternative_names: ["U10", "u10", "uas","uwnd"]
    standardize: true
    lr_only: true

  vas:
    hr:
      path: /Volumes/LaCie/nonan/vas/*small3.nc
      is_west_negative: false
    lr:
      path: /Volumes/LaCie/nonan/vas/*small3.nc
      is_west_negative: false
    output_path: /Volumes/LaCie/2years_smallest_coarsened_southatlantic/
    alternative_names: ["V10", "v10", "vas","vwnd"]
    standardize: true
    lr_only: true

#  ice:
#    hr:
#      path: /Volumes/LaCie/nonan/ice/*smallest.nc
#      is_west_negative: false
#    lr:
#      path: /Volumes/LaCie/nonan/ice/*smallest.nc
#      is_west_negative: false
#    output_path: /Volumes/LaCie/2year_coarsened_cropped/
#    alternative_names: ["ice","SIC"]
#    standardize: true
#
#  t0m1:
#    hr:
#      path: /Volumes/LaCie/nonan/t0m1/*smallest.nc
#      is_west_negative: false
#    lr:
#      path: /Volumes/LaCie/nonan/t0m1/*smallest.nc
#      is_west_negative: false
#    output_path: /Volumes/LaCie/2year_coarsened_cropped/
#    alternative_names: ["t0m1"]
#    standardize: true
#
#  dir:
#    hr:
#      path: /Volumes/LaCie/nonan/dir/*smallest.nc
#      is_west_negative: false
#    lr:
#      path: /Volumes/LaCie/nonan/dir/*smallest.nc
#      is_west_negative: false
#    output_path: /Volumes/LaCie/2year_coarsened_cropped/
#    alternative_names: ["dir"]
#    standardize: true
#

  # MAPSTA:
  #   hr:
  #     path: /Volumes/LaCie/nonan/MAPSTA/*small3.nc
  #     is_west_negative: false
  #   lr:
  #     path: /Volumes/LaCie/nonan/MAPSTA/*small3.nc
  #     is_west_negative: false
  #   output_path: /Volumes/LaCie/2years_smallest_coarsened_southatlantic/
  #   alternative_names: ["MAPSTA"]
  #   standardize: true

dims:
  time:
    alternative_names: ["Time", "Times", "times"]
  rlat:
    alternative_names: ["rotated_latitude"]
    hr_only: true
  rlon:
    alternative_names: ["rotated_longitude"]
    hr_only: true
coords:
  lat:
    alternative_names: ["latitude", "Lat", "Latitude"]
  lon:
    alternative_names: ["longitude", "Long", "Lon", "Longitude"]

# Time indexing for subsets
time:
  # Crop to the dataset with the shortest run
  # this defines the full dataset from which to subset
  full:
    start: "19950101T00:00:00"
    end: "19961231T21:00:00"

  # use this to select which years to reserve for testing
  # the remaining years in full will be used for training
  test_years: []

# sets the scale factor and index slices of the rotated coordinates
spatial:
  scale_factor: 8
  x:
    first_index: 0
    last_index: 128
  y:
    first_index: 0
    last_index: 128

# xarray netcdf engine
engine: netcdf4
steps_per_file: 32
randomize: true

# dask client parameters
compute:
  threads_per_worker: 1
  memory_limit: "8GB"
  dashboard_address: 8787

# define torch
loader:
  batch_size: 50
  randomize: true
  seed: 0
